### ISSUE TITLE
Regarding inference

### ISSUE THREAD

**Issue by BakingBrains** [AI4Bharat/vistaar#1]
Hello,
How can I get the timestamp.

I even used transformers pipeline.

```
from transformers import pipeline
import torch

model = pipeline(
    task="automatic-speech-recognition",
    model="vistar/hindi", 
    device=torch.device("cuda:0"),
    chunk_length_s=30, # if not precised then only generate as much as `max_new_tokens`
    generate_kwargs={"num_beams": 5} # same setting as `openai-whisper` default
)

result = model("audio.mp3", return_timestamps=True)

print(result["text"])
print(result["chunks"])
```

transcription is good. But It is not returning timestamp.
Any suggestions here?

Thank you

**Comment by kaushal-py** [comment]
We do not support timestamps for this model, as it is specific to just the ASR task. To get timestamps, you can first manually chunk the audio using Voice Activity Detection tools like WebRTCVAD or Silero VAD, and then pass those chunks to the IndicWhisper models.
